"""check

Revision ID: 16526a330d17
Revises: 3a616805b9be
Create Date: 2025-12-11 12:58:35.044958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16526a330d17'
down_revision = '3a616805b9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_member_profiles', schema=None) as batch_op:
        batch_op.alter_column('joining_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
                postgresql_using="joining_date::timestamp without time zone"
               )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_member_profiles', schema=None) as batch_op:
        batch_op.alter_column('joining_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
