"""Changes

Revision ID: 3a616805b9be
Revises: 49c464c34c84
Create Date: 2025-12-11 12:43:28.709739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a616805b9be'
down_revision = '49c464c34c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_member_profiles', schema=None) as batch_op:
        batch_op.alter_column('joining_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True,
                
               )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_member_profiles', schema=None) as batch_op:
        batch_op.alter_column('joining_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True
               )

    # ### end Alembic commands ###
