"""changes phone data type to string in user model 

Revision ID: 49c464c34c84
Revises: 02e0ffaf6b1d
Create Date: 2025-12-08 12:01:23.546875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c464c34c84'
down_revision = '02e0ffaf6b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_number',
               existing_type=sa.String(length=14),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
