"""creates ledger account table migration set up 

Revision ID: aa42790421f9
Revises: 16526a330d17
Create Date: 2025-12-18 14:26:02.028401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa42790421f9'
down_revision = '16526a330d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.Enum('MEMBER', 'ORG', name='ledgerownertype'), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.Enum('SAVINGS', name='ledgeraccounttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(owner_type = 'MEMBER' AND member_id IS NOT NULL) OR (owner_type = 'ORG' AND member_id IS NULL)", name='ck_ledger_owner'),
    sa.ForeignKeyConstraint(['member_id'], ['sacco_member_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
