"""adds name column to ledger acc table 

Revision ID: e2e39261f881
Revises: aa42790421f9
Create Date: 2025-12-18 21:20:17.721485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e39261f881'
down_revision = 'aa42790421f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
